/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import WXFUI_damageView from "./WXFUI_damageView";
import WXFUI_addGold from "./WXFUI_addGold";
import WXFUI_RewardView from "./WXFUI_RewardView";
import WXFUI_quedingBtn from "./WXFUI_quedingBtn";
import WXFUI_enemy_fire_14 from "./WXFUI_enemy_fire_14";
import WXFUI_star from "./WXFUI_star";
import WXFUI_jumpBtn from "./WXFUI_jumpBtn";
import WXFUI_fireBtn from "./WXFUI_fireBtn";
import WXFUI_throwBtn from "./WXFUI_throwBtn";
import WXFUI_enemyStay_5 from "./WXFUI_enemyStay_5";
import WXFUI_enemy_fire_5 from "./WXFUI_enemy_fire_5";
import WXFUI_enemy5 from "./WXFUI_enemy5";
import WXFUI_backHomeBtn from "./WXFUI_backHomeBtn";
import WXFUI_restartBtn from "./WXFUI_restartBtn";
import WXFUI_continueBtn from "./WXFUI_continueBtn";
import WXFUI_BeforeWar from "./WXFUI_BeforeWar";
import WXFUI_buyItem from "./WXFUI_buyItem";
import WXFUI_enterBtn from "./WXFUI_enterBtn";
import WXFUI_buyBtn from "./WXFUI_buyBtn";
import WXFUI_freeBtn from "./WXFUI_freeBtn";
import WXFUI_AfterWar from "./WXFUI_AfterWar";
import WXFUI_backBtn from "./WXFUI_backBtn";
import WXFUI_continueBtn2 from "./WXFUI_continueBtn2";
import WXFUI_continueBtn3 from "./WXFUI_continueBtn3";
import WXFUI_continueBtn4 from "./WXFUI_continueBtn4";
import WXFUI_ChapterView from "./WXFUI_ChapterView";
import WXFUI_LevelItem from "./WXFUI_LevelItem";
import WXFUI_lastChapter from "./WXFUI_lastChapter";
import WXFUI_nextChapter from "./WXFUI_nextChapter";
import WXFUI_share from "./WXFUI_share";
import WXFUI_shareBtn1 from "./WXFUI_shareBtn1";
import WXFUI_shareBtn2 from "./WXFUI_shareBtn2";
import WXFUI_enemy11 from "./WXFUI_enemy11";
import WXFUI_enemy12 from "./WXFUI_enemy12";
import WXFUI_Bomb from "./WXFUI_Bomb";
import WXFUI_PlayerInfoView from "./WXFUI_PlayerInfoView";
import WXFUI_PlayerCtlView from "./WXFUI_PlayerCtlView";
import WXFUI_PlayerDirView from "./WXFUI_PlayerDirView";
import WXFUI_dirBtn from "./WXFUI_dirBtn";
import WXFUI_susBtn from "./WXFUI_susBtn";
import WXFUI_ADListHorBig2 from "./WXFUI_ADListHorBig2";
import WXFUI_ADItemBig2 from "./WXFUI_ADItemBig2";
import WXFUI_freeView from "./WXFUI_freeView";
import WXFUI_videoBtn from "./WXFUI_videoBtn";
import WXFUI_lingquBtn from "./WXFUI_lingquBtn";
import WXFUI_fangqiBtn from "./WXFUI_fangqiBtn";
import WXFUI_guanbiBtn from "./WXFUI_guanbiBtn";
import WXFUI_noVideoTips from "./WXFUI_noVideoTips";
import WXFUI_guanbi2Btn from "./WXFUI_guanbi2Btn";
import WXFUI_queding2Btn from "./WXFUI_queding2Btn";
import WXFUI_showVideoView from "./WXFUI_showVideoView";
import WXFUI_queding3Btn from "./WXFUI_queding3Btn";
import WXFUI_recordView from "./WXFUI_recordView";
import WXFUI_nextBtn from "./WXFUI_nextBtn";
import WXFUI_chaBtn from "./WXFUI_chaBtn";
import WXFUI_BoomView from "./WXFUI_BoomView";
import WXFUI_ADReMenList from "./WXFUI_ADReMenList";
import WXFUI_ADremen2 from "./WXFUI_ADremen2";
import WXFUI_ADListHorBig from "./WXFUI_ADListHorBig";
import WXFUI_ADItemBig from "./WXFUI_ADItemBig";
import WXFUI_OppoNativeADView from "./WXFUI_OppoNativeADView";
import WXFUI_sanBeiBtn from "./WXFUI_sanBeiBtn";
import WXFUI_nextBtn2 from "./WXFUI_nextBtn2";
import WXFUI_ClickADView from "./WXFUI_ClickADView";
import WXFUI_clickBar from "./WXFUI_clickBar";
import WXFUI_clickBtn from "./WXFUI_clickBtn";
import WXFUI_NativeADView from "./WXFUI_NativeADView";
import WXFUI_seeAdBtn from "./WXFUI_seeAdBtn";
import WXFUI_nativeClose from "./WXFUI_nativeClose";
import WXFUI_PopUpView from "./WXFUI_PopUpView";
import WXFUI_SuspendView from "./WXFUI_SuspendView";
import WXFUI_enemy1 from "./WXFUI_enemy1";
import WXFUI_enemy2 from "./WXFUI_enemy2";
import WXFUI_enemy3 from "./WXFUI_enemy3";
import WXFUI_enemy4 from "./WXFUI_enemy4";
import WXFUI_enemy from "./WXFUI_enemy";
import WXFUI_WarView from "./WXFUI_WarView";
import WXFUI_goodsView from "./WXFUI_goodsView";
import WXFUI_enemy10 from "./WXFUI_enemy10";
import WXFUI_enemy_fire_11 from "./WXFUI_enemy_fire_11";
import WXFUI_enemy_fire_12 from "./WXFUI_enemy_fire_12";
import WXFUI_obstacleView from "./WXFUI_obstacleView";
import WXFUI_ADItem from "./WXFUI_ADItem";
import WXFUI_ADmove from "./WXFUI_ADmove";
import WXFUI_ADListVer from "./WXFUI_ADListVer";
import WXFUI_ADListHor from "./WXFUI_ADListHor";
import WXFUI_ADremen from "./WXFUI_ADremen";
import WXFUI_GoodsItem from "./WXFUI_GoodsItem";
import WXFUI_blood from "./WXFUI_blood";
import WXFUI_enemy6 from "./WXFUI_enemy6";
import WXFUI_enemy13 from "./WXFUI_enemy13";
import WXFUI_enemy14 from "./WXFUI_enemy14";
import WXFUI_enemy_fire_13 from "./WXFUI_enemy_fire_13";
import WXFUI_TipsPopView from "./WXFUI_TipsPopView";
import WXFUI_volume from "./WXFUI_volume";
import WXFUI_abandon from "./WXFUI_abandon";
import WXFUI_hostage from "./WXFUI_hostage";
import WXFUI_ClickChestView from "./WXFUI_ClickChestView";
import WXFUI_loadingBar from "./WXFUI_loadingBar";
import WXFUI_openChestBtn from "./WXFUI_openChestBtn";
import WXFUI_ADListView from "./WXFUI_ADListView";
import WXFUI_sandan from "./WXFUI_sandan";
import WXFUI_zidan from "./WXFUI_zidan";

export default class GameBinder{
	public static bindAll():void {
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_damageView.URL, WXFUI_damageView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_addGold.URL, WXFUI_addGold);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_RewardView.URL, WXFUI_RewardView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_quedingBtn.URL, WXFUI_quedingBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_14.URL, WXFUI_enemy_fire_14);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_star.URL, WXFUI_star);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_jumpBtn.URL, WXFUI_jumpBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_fireBtn.URL, WXFUI_fireBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_throwBtn.URL, WXFUI_throwBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemyStay_5.URL, WXFUI_enemyStay_5);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_5.URL, WXFUI_enemy_fire_5);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy5.URL, WXFUI_enemy5);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_backHomeBtn.URL, WXFUI_backHomeBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_restartBtn.URL, WXFUI_restartBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_continueBtn.URL, WXFUI_continueBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_BeforeWar.URL, WXFUI_BeforeWar);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_buyItem.URL, WXFUI_buyItem);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enterBtn.URL, WXFUI_enterBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_buyBtn.URL, WXFUI_buyBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_freeBtn.URL, WXFUI_freeBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_AfterWar.URL, WXFUI_AfterWar);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_backBtn.URL, WXFUI_backBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_continueBtn2.URL, WXFUI_continueBtn2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_continueBtn3.URL, WXFUI_continueBtn3);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_continueBtn4.URL, WXFUI_continueBtn4);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ChapterView.URL, WXFUI_ChapterView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_LevelItem.URL, WXFUI_LevelItem);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_lastChapter.URL, WXFUI_lastChapter);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_nextChapter.URL, WXFUI_nextChapter);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_share.URL, WXFUI_share);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_shareBtn1.URL, WXFUI_shareBtn1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_shareBtn2.URL, WXFUI_shareBtn2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy11.URL, WXFUI_enemy11);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy12.URL, WXFUI_enemy12);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_Bomb.URL, WXFUI_Bomb);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_PlayerInfoView.URL, WXFUI_PlayerInfoView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_PlayerCtlView.URL, WXFUI_PlayerCtlView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_PlayerDirView.URL, WXFUI_PlayerDirView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_dirBtn.URL, WXFUI_dirBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_susBtn.URL, WXFUI_susBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADListHorBig2.URL, WXFUI_ADListHorBig2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADItemBig2.URL, WXFUI_ADItemBig2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_freeView.URL, WXFUI_freeView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_videoBtn.URL, WXFUI_videoBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_lingquBtn.URL, WXFUI_lingquBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_fangqiBtn.URL, WXFUI_fangqiBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_guanbiBtn.URL, WXFUI_guanbiBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_noVideoTips.URL, WXFUI_noVideoTips);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_guanbi2Btn.URL, WXFUI_guanbi2Btn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_queding2Btn.URL, WXFUI_queding2Btn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_showVideoView.URL, WXFUI_showVideoView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_queding3Btn.URL, WXFUI_queding3Btn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_recordView.URL, WXFUI_recordView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_nextBtn.URL, WXFUI_nextBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_chaBtn.URL, WXFUI_chaBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_BoomView.URL, WXFUI_BoomView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADReMenList.URL, WXFUI_ADReMenList);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADremen2.URL, WXFUI_ADremen2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADListHorBig.URL, WXFUI_ADListHorBig);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADItemBig.URL, WXFUI_ADItemBig);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_OppoNativeADView.URL, WXFUI_OppoNativeADView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_sanBeiBtn.URL, WXFUI_sanBeiBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_nextBtn2.URL, WXFUI_nextBtn2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ClickADView.URL, WXFUI_ClickADView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_clickBar.URL, WXFUI_clickBar);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_clickBtn.URL, WXFUI_clickBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_NativeADView.URL, WXFUI_NativeADView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_seeAdBtn.URL, WXFUI_seeAdBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_nativeClose.URL, WXFUI_nativeClose);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_PopUpView.URL, WXFUI_PopUpView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_SuspendView.URL, WXFUI_SuspendView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy1.URL, WXFUI_enemy1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy2.URL, WXFUI_enemy2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy3.URL, WXFUI_enemy3);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy4.URL, WXFUI_enemy4);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy.URL, WXFUI_enemy);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_WarView.URL, WXFUI_WarView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_goodsView.URL, WXFUI_goodsView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy10.URL, WXFUI_enemy10);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_11.URL, WXFUI_enemy_fire_11);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_12.URL, WXFUI_enemy_fire_12);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_obstacleView.URL, WXFUI_obstacleView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADItem.URL, WXFUI_ADItem);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADmove.URL, WXFUI_ADmove);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADListVer.URL, WXFUI_ADListVer);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADListHor.URL, WXFUI_ADListHor);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADremen.URL, WXFUI_ADremen);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_GoodsItem.URL, WXFUI_GoodsItem);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_blood.URL, WXFUI_blood);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy6.URL, WXFUI_enemy6);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy13.URL, WXFUI_enemy13);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy14.URL, WXFUI_enemy14);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_13.URL, WXFUI_enemy_fire_13);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_TipsPopView.URL, WXFUI_TipsPopView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_volume.URL, WXFUI_volume);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_abandon.URL, WXFUI_abandon);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_hostage.URL, WXFUI_hostage);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ClickChestView.URL, WXFUI_ClickChestView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_loadingBar.URL, WXFUI_loadingBar);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_openChestBtn.URL, WXFUI_openChestBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_ADListView.URL, WXFUI_ADListView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_sandan.URL, WXFUI_sandan);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_zidan.URL, WXFUI_zidan);
	}
}