/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import WXFUI_damageView from "./WXFUI_damageView";
import WXFUI_addGold from "./WXFUI_addGold";
import WXFUI_enemy_fire_14 from "./WXFUI_enemy_fire_14";
import WXFUI_star from "./WXFUI_star";
import WXFUI_jumpBtn from "./WXFUI_jumpBtn";
import WXFUI_fireBtn from "./WXFUI_fireBtn";
import WXFUI_throwBtn from "./WXFUI_throwBtn";
import WXFUI_enemyStay_5 from "./WXFUI_enemyStay_5";
import WXFUI_enemy_fire_5 from "./WXFUI_enemy_fire_5";
import WXFUI_enemy5 from "./WXFUI_enemy5";
import WXFUI_backHomeBtn from "./WXFUI_backHomeBtn";
import WXFUI_restartBtn from "./WXFUI_restartBtn";
import WXFUI_continueBtn from "./WXFUI_continueBtn";
import WXFUI_BeforeWar from "./WXFUI_BeforeWar";
import WXFUI_buyItem from "./WXFUI_buyItem";
import WXFUI_enterBtn from "./WXFUI_enterBtn";
import WXFUI_buyBtn from "./WXFUI_buyBtn";
import WXFUI_freeBtn from "./WXFUI_freeBtn";
import WXFUI_AfterWar from "./WXFUI_AfterWar";
import WXFUI_backBtn from "./WXFUI_backBtn";
import WXFUI_continueBtn2 from "./WXFUI_continueBtn2";
import WXFUI_continueBtn3 from "./WXFUI_continueBtn3";
import WXFUI_continueBtn4 from "./WXFUI_continueBtn4";
import WXFUI_ChapterView from "./WXFUI_ChapterView";
import WXFUI_LevelItem from "./WXFUI_LevelItem";
import WXFUI_lastChapter from "./WXFUI_lastChapter";
import WXFUI_nextChapter from "./WXFUI_nextChapter";
import WXFUI_share from "./WXFUI_share";
import WXFUI_shareBtn1 from "./WXFUI_shareBtn1";
import WXFUI_shareBtn2 from "./WXFUI_shareBtn2";
import WXFUI_enemy11 from "./WXFUI_enemy11";
import WXFUI_enemy12 from "./WXFUI_enemy12";
import WXFUI_Bomb from "./WXFUI_Bomb";
import WXFUI_PlayerInfoView from "./WXFUI_PlayerInfoView";
import WXFUI_PlayerCtlView from "./WXFUI_PlayerCtlView";
import WXFUI_PlayerDirView from "./WXFUI_PlayerDirView";
import WXFUI_dirBtn from "./WXFUI_dirBtn";
import WXFUI_susBtn from "./WXFUI_susBtn";
import WXFUI_ADListHorBig2 from "./WXFUI_ADListHorBig2";
import WXFUI_ADItemBig2 from "./WXFUI_ADItemBig2";
import WXFUI_BoomView from "./WXFUI_BoomView";
import WXFUI_ADReMenList from "./WXFUI_ADReMenList";
import WXFUI_ADremen2 from "./WXFUI_ADremen2";
import WXFUI_ADListHorBig from "./WXFUI_ADListHorBig";
import WXFUI_ADItemBig from "./WXFUI_ADItemBig";
import WXFUI_ClickADView from "./WXFUI_ClickADView";
import WXFUI_clickBar from "./WXFUI_clickBar";
import WXFUI_clickBtn from "./WXFUI_clickBtn";
import WXFUI_PopUpView from "./WXFUI_PopUpView";
import WXFUI_SuspendView from "./WXFUI_SuspendView";
import WXFUI_enemy1 from "./WXFUI_enemy1";
import WXFUI_enemy2 from "./WXFUI_enemy2";
import WXFUI_enemy3 from "./WXFUI_enemy3";
import WXFUI_enemy4 from "./WXFUI_enemy4";
import WXFUI_enemy from "./WXFUI_enemy";
import WXFUI_WarView from "./WXFUI_WarView";
import WXFUI_goodsView from "./WXFUI_goodsView";
import WXFUI_enemy10 from "./WXFUI_enemy10";
import WXFUI_enemy_fire_11 from "./WXFUI_enemy_fire_11";
import WXFUI_enemy_fire_12 from "./WXFUI_enemy_fire_12";
import WXFUI_obstacleView from "./WXFUI_obstacleView";
import WXFUI_ADItem from "./WXFUI_ADItem";
import WXFUI_ADmove from "./WXFUI_ADmove";
import WXFUI_ADListVer from "./WXFUI_ADListVer";
import WXFUI_ADListHor from "./WXFUI_ADListHor";
import WXFUI_ADremen from "./WXFUI_ADremen";
import WXFUI_blood from "./WXFUI_blood";
import WXFUI_enemy6 from "./WXFUI_enemy6";
import WXFUI_enemy13 from "./WXFUI_enemy13";
import WXFUI_enemy14 from "./WXFUI_enemy14";
import WXFUI_enemy_fire_13 from "./WXFUI_enemy_fire_13";
import WXFUI_TipsPopView from "./WXFUI_TipsPopView";
import WXFUI_volume from "./WXFUI_volume";
import WXFUI_abandon from "./WXFUI_abandon";
import WXFUI_hostage from "./WXFUI_hostage";
import WXFUI_ClickChestView from "./WXFUI_ClickChestView";
import WXFUI_loadingBar from "./WXFUI_loadingBar";
import WXFUI_openChestBtn from "./WXFUI_openChestBtn";
import WXFUI_ADListView from "./WXFUI_ADListView";
import WXFUI_sandan from "./WXFUI_sandan";
import WXFUI_zidan from "./WXFUI_zidan";

export default class GameBinder {
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(WXFUI_damageView.URL, WXFUI_damageView);
		fgui.UIObjectFactory.setExtension(WXFUI_addGold.URL, WXFUI_addGold);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy_fire_14.URL, WXFUI_enemy_fire_14);
		fgui.UIObjectFactory.setExtension(WXFUI_star.URL, WXFUI_star);
		fgui.UIObjectFactory.setExtension(WXFUI_jumpBtn.URL, WXFUI_jumpBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_fireBtn.URL, WXFUI_fireBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_throwBtn.URL, WXFUI_throwBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_enemyStay_5.URL, WXFUI_enemyStay_5);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy_fire_5.URL, WXFUI_enemy_fire_5);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy5.URL, WXFUI_enemy5);
		fgui.UIObjectFactory.setExtension(WXFUI_backHomeBtn.URL, WXFUI_backHomeBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_restartBtn.URL, WXFUI_restartBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_continueBtn.URL, WXFUI_continueBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_BeforeWar.URL, WXFUI_BeforeWar);
		fgui.UIObjectFactory.setExtension(WXFUI_buyItem.URL, WXFUI_buyItem);
		fgui.UIObjectFactory.setExtension(WXFUI_enterBtn.URL, WXFUI_enterBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_buyBtn.URL, WXFUI_buyBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_freeBtn.URL, WXFUI_freeBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_AfterWar.URL, WXFUI_AfterWar);
		fgui.UIObjectFactory.setExtension(WXFUI_backBtn.URL, WXFUI_backBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_continueBtn2.URL, WXFUI_continueBtn2);
		fgui.UIObjectFactory.setExtension(WXFUI_continueBtn3.URL, WXFUI_continueBtn3);
		fgui.UIObjectFactory.setExtension(WXFUI_continueBtn4.URL, WXFUI_continueBtn4);
		fgui.UIObjectFactory.setExtension(WXFUI_ChapterView.URL, WXFUI_ChapterView);
		fgui.UIObjectFactory.setExtension(WXFUI_LevelItem.URL, WXFUI_LevelItem);
		fgui.UIObjectFactory.setExtension(WXFUI_lastChapter.URL, WXFUI_lastChapter);
		fgui.UIObjectFactory.setExtension(WXFUI_nextChapter.URL, WXFUI_nextChapter);
		fgui.UIObjectFactory.setExtension(WXFUI_share.URL, WXFUI_share);
		fgui.UIObjectFactory.setExtension(WXFUI_shareBtn1.URL, WXFUI_shareBtn1);
		fgui.UIObjectFactory.setExtension(WXFUI_shareBtn2.URL, WXFUI_shareBtn2);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy11.URL, WXFUI_enemy11);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy12.URL, WXFUI_enemy12);
		fgui.UIObjectFactory.setExtension(WXFUI_Bomb.URL, WXFUI_Bomb);
		fgui.UIObjectFactory.setExtension(WXFUI_PlayerInfoView.URL, WXFUI_PlayerInfoView);
		fgui.UIObjectFactory.setExtension(WXFUI_PlayerCtlView.URL, WXFUI_PlayerCtlView);
		fgui.UIObjectFactory.setExtension(WXFUI_PlayerDirView.URL, WXFUI_PlayerDirView);
		fgui.UIObjectFactory.setExtension(WXFUI_dirBtn.URL, WXFUI_dirBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_susBtn.URL, WXFUI_susBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_ADListHorBig2.URL, WXFUI_ADListHorBig2);
		fgui.UIObjectFactory.setExtension(WXFUI_ADItemBig2.URL, WXFUI_ADItemBig2);
		fgui.UIObjectFactory.setExtension(WXFUI_BoomView.URL, WXFUI_BoomView);
		fgui.UIObjectFactory.setExtension(WXFUI_ADReMenList.URL, WXFUI_ADReMenList);
		fgui.UIObjectFactory.setExtension(WXFUI_ADremen2.URL, WXFUI_ADremen2);
		fgui.UIObjectFactory.setExtension(WXFUI_ADListHorBig.URL, WXFUI_ADListHorBig);
		fgui.UIObjectFactory.setExtension(WXFUI_ADItemBig.URL, WXFUI_ADItemBig);
		fgui.UIObjectFactory.setExtension(WXFUI_ClickADView.URL, WXFUI_ClickADView);
		fgui.UIObjectFactory.setExtension(WXFUI_clickBar.URL, WXFUI_clickBar);
		fgui.UIObjectFactory.setExtension(WXFUI_clickBtn.URL, WXFUI_clickBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_PopUpView.URL, WXFUI_PopUpView);
		fgui.UIObjectFactory.setExtension(WXFUI_SuspendView.URL, WXFUI_SuspendView);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy1.URL, WXFUI_enemy1);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy2.URL, WXFUI_enemy2);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy3.URL, WXFUI_enemy3);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy4.URL, WXFUI_enemy4);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy.URL, WXFUI_enemy);
		fgui.UIObjectFactory.setExtension(WXFUI_WarView.URL, WXFUI_WarView);
		fgui.UIObjectFactory.setExtension(WXFUI_goodsView.URL, WXFUI_goodsView);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy10.URL, WXFUI_enemy10);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy_fire_11.URL, WXFUI_enemy_fire_11);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy_fire_12.URL, WXFUI_enemy_fire_12);
		fgui.UIObjectFactory.setExtension(WXFUI_obstacleView.URL, WXFUI_obstacleView);
		fgui.UIObjectFactory.setExtension(WXFUI_ADItem.URL, WXFUI_ADItem);
		fgui.UIObjectFactory.setExtension(WXFUI_ADmove.URL, WXFUI_ADmove);
		fgui.UIObjectFactory.setExtension(WXFUI_ADListVer.URL, WXFUI_ADListVer);
		fgui.UIObjectFactory.setExtension(WXFUI_ADListHor.URL, WXFUI_ADListHor);
		fgui.UIObjectFactory.setExtension(WXFUI_ADremen.URL, WXFUI_ADremen);
		fgui.UIObjectFactory.setExtension(WXFUI_blood.URL, WXFUI_blood);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy6.URL, WXFUI_enemy6);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy13.URL, WXFUI_enemy13);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy14.URL, WXFUI_enemy14);
		fgui.UIObjectFactory.setExtension(WXFUI_enemy_fire_13.URL, WXFUI_enemy_fire_13);
		fgui.UIObjectFactory.setExtension(WXFUI_TipsPopView.URL, WXFUI_TipsPopView);
		fgui.UIObjectFactory.setExtension(WXFUI_volume.URL, WXFUI_volume);
		fgui.UIObjectFactory.setExtension(WXFUI_abandon.URL, WXFUI_abandon);
		fgui.UIObjectFactory.setExtension(WXFUI_hostage.URL, WXFUI_hostage);
		fgui.UIObjectFactory.setExtension(WXFUI_ClickChestView.URL, WXFUI_ClickChestView);
		fgui.UIObjectFactory.setExtension(WXFUI_loadingBar.URL, WXFUI_loadingBar);
		fgui.UIObjectFactory.setExtension(WXFUI_openChestBtn.URL, WXFUI_openChestBtn);
		fgui.UIObjectFactory.setExtension(WXFUI_ADListView.URL, WXFUI_ADListView);
		fgui.UIObjectFactory.setExtension(WXFUI_sandan.URL, WXFUI_sandan);
		fgui.UIObjectFactory.setExtension(WXFUI_zidan.URL, WXFUI_zidan);
	}
}