/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import WXFUI_jumpBtn from "./WXFUI_jumpBtn";
import WXFUI_fireBtn from "./WXFUI_fireBtn";
import WXFUI_throwBtn from "./WXFUI_throwBtn";
import WXFUI_player_stay_1 from "./WXFUI_player_stay_1";
import WXFUI_player_stay_2 from "./WXFUI_player_stay_2";
import WXFUI_enemyStay_5 from "./WXFUI_enemyStay_5";
import WXFUI_enemy_fire_5 from "./WXFUI_enemy_fire_5";
import WXFUI_enemy5 from "./WXFUI_enemy5";
import WXFUI_player_stay_3 from "./WXFUI_player_stay_3";
import WXFUI_enemy11 from "./WXFUI_enemy11";
import WXFUI_enemy12 from "./WXFUI_enemy12";
import WXFUI_Bomb from "./WXFUI_Bomb";
import WXFUI_PlayerInfoView from "./WXFUI_PlayerInfoView";
import WXFUI_PlayerCtlView from "./WXFUI_PlayerCtlView";
import WXFUI_dirCtlView from "./WXFUI_dirCtlView";
import WXFUI_dirBtn from "./WXFUI_dirBtn";
import WXFUI_susBtn from "./WXFUI_susBtn";
import WXFUI_BoomView from "./WXFUI_BoomView";
import WXFUI_player_fire_3 from "./WXFUI_player_fire_3";
import WXFUI_player_fire_1 from "./WXFUI_player_fire_1";
import WXFUI_player_fire_2 from "./WXFUI_player_fire_2";
import WXFUI_Player from "./WXFUI_Player";
import WXFUI_player_boom_1 from "./WXFUI_player_boom_1";
import WXFUI_player_boom_2 from "./WXFUI_player_boom_2";
import WXFUI_enemy1 from "./WXFUI_enemy1";
import WXFUI_enemy2 from "./WXFUI_enemy2";
import WXFUI_enemy3 from "./WXFUI_enemy3";
import WXFUI_enemy4 from "./WXFUI_enemy4";
import WXFUI_enemy from "./WXFUI_enemy";
import WXFUI_WarView from "./WXFUI_WarView";
import WXFUI_goodsView from "./WXFUI_goodsView";
import WXFUI_enemy10 from "./WXFUI_enemy10";
import WXFUI_enemy_fire_11 from "./WXFUI_enemy_fire_11";
import WXFUI_enemy_fire_12 from "./WXFUI_enemy_fire_12";
import WXFUI_obstacle from "./WXFUI_obstacle";
import WXFUI_bullet1 from "./WXFUI_bullet1";
import WXFUI_bullet2 from "./WXFUI_bullet2";
import WXFUI_zidan from "./WXFUI_zidan";

export default class GameBinder{
	public static bindAll():void {
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_jumpBtn.URL, WXFUI_jumpBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_fireBtn.URL, WXFUI_fireBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_throwBtn.URL, WXFUI_throwBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_stay_1.URL, WXFUI_player_stay_1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_stay_2.URL, WXFUI_player_stay_2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemyStay_5.URL, WXFUI_enemyStay_5);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_5.URL, WXFUI_enemy_fire_5);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy5.URL, WXFUI_enemy5);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_stay_3.URL, WXFUI_player_stay_3);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy11.URL, WXFUI_enemy11);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy12.URL, WXFUI_enemy12);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_Bomb.URL, WXFUI_Bomb);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_PlayerInfoView.URL, WXFUI_PlayerInfoView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_PlayerCtlView.URL, WXFUI_PlayerCtlView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_dirCtlView.URL, WXFUI_dirCtlView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_dirBtn.URL, WXFUI_dirBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_susBtn.URL, WXFUI_susBtn);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_BoomView.URL, WXFUI_BoomView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_fire_3.URL, WXFUI_player_fire_3);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_fire_1.URL, WXFUI_player_fire_1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_fire_2.URL, WXFUI_player_fire_2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_Player.URL, WXFUI_Player);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_boom_1.URL, WXFUI_player_boom_1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_player_boom_2.URL, WXFUI_player_boom_2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy1.URL, WXFUI_enemy1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy2.URL, WXFUI_enemy2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy3.URL, WXFUI_enemy3);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy4.URL, WXFUI_enemy4);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy.URL, WXFUI_enemy);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_WarView.URL, WXFUI_WarView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_goodsView.URL, WXFUI_goodsView);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy10.URL, WXFUI_enemy10);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_11.URL, WXFUI_enemy_fire_11);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_enemy_fire_12.URL, WXFUI_enemy_fire_12);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_obstacle.URL, WXFUI_obstacle);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_bullet1.URL, WXFUI_bullet1);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_bullet2.URL, WXFUI_bullet2);
		fairygui.UIObjectFactory.setPackageItemExtension(WXFUI_zidan.URL, WXFUI_zidan);
	}
}