/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

/*
* 游戏初始化配置;
*/
export default class GameConfig {
    static width: number = 1334;
    static height: number = 750;
    static scaleMode: string = Laya.Stage.SCALE_EXACTFIT;
    static screenMode: string = Laya.Stage.SCREEN_HORIZONTAL;
    static alignV: string = Laya.Stage.ALIGN_CENTER;
    static alignH: string = Laya.Stage.ALIGN_MIDDLE;
    static startScene: any = "";
    static sceneRoot: string = "";
    static debug: boolean = false;
    static stat: boolean = false;
    static physicsDebug: boolean = false;
    static exportSceneToJson: boolean = true;
    constructor() { }
    static init() {
        var reg: Function = Laya.ClassUtils.regClass;

    }
}
GameConfig.init();